repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.11
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
        stages: [pre-commit]

  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -c 'pip install pytest-asyncio asyncpg greenlet -e . && python -m pytest'
        language: system
        pass_filenames: false
        always_run: true
        additional_dependencies: []

  - repo: local
    hooks:
      - id: check-templates
        name: check-templates
        entry: python scripts/check_templates.py
        language: python
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
