repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: templates/.*\.yml$
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        stages: [pre-commit]
        files: \.(?:ts|js|json|yaml|yml|md)$
        exclude: \.lock$

  #  - repo: https://github.com/pre-commit/mirrors-eslint
  #    rev: v8
  #    hooks:
  #      - id: eslint
  #        stages: [pre-commit]
  #        files: \.(?:ts|js)$
  #        args: [--fix]
  #        additional_dependencies:
  #          - eslint@^9.0.0
  #          - "@typescript-eslint/parser@^8.0.0"
  #          - "@typescript-eslint/eslint-plugin@^8.0.0"
  #          - eslint-config-prettier
  #          - eslint-plugin-prettier

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
        stages: [pre-commit]

  #  - repo: https://github.com/psf/black
  #    rev: 24.1.1
  #    hooks:
  #      - id: black
  #        stages: [pre-commit]

  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: pytest
  #       entry: bash -c 'cd "$(git rev-parse --show-toplevel)" && export SUPABASE_URL="postgresql://testuser:testpassword@localhost:5432/testdb" && export TEST_DATABASE_URL="postgresql+asyncpg://testuser:testpassword@localhost:5432/testdb" && export REDIS_URL="redis://localhost:6379/0" && export JWT_SECRET="testsecretprecommit" && export DOCASSEMBLE_URL="http://localhost:5000" && poetry install --no-root --sync && poetry run pytest --cov-report= --no-cov-on-fail -m "not integration and not rls" -k "not test_db_pool_close_called and not test_sdk_login_parity"'
  #       language: system
  #       pass_filenames: false
  #       always_run: true
  #       require_serial: true
