"""add_amount_to_doc_table.

Revision ID: a8ffc5416e84
Revises: 0001_initial_schema
Create Date: 2025-05-06 10:52:15.511477

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8ffc5416e84"
down_revision: Union[str, None] = "0001_initial_schema"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the migration: add amount column to doc table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "doc", sa.Column("amount", sa.NUMERIC(precision=10, scale=2), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration: remove amount column from doc table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("doc", "amount")
    # ### end Alembic commands ###
